import {
  FETCH_QUESTIONS_BEGIN,
  FETCH_QUESTIONS_SUCCESS,
  FETCH_QUESTIONS_FAILURE,
  UPDATE_QUESTION_DICTIONARY
} from 'constants/index';

test('constants', () => {
  expect(FETCH_QUESTIONS_BEGIN).toBe('FETCH_QUESTIONS_BEGIN');
  expect(FETCH_QUESTIONS_SUCCESS).toBe('FETCH_QUESTIONS_SUCCESS');
  expect(FETCH_QUESTIONS_FAILURE).toBe('FETCH_QUESTIONS_FAILURE');
  expect(UPDATE_QUESTION_DICTIONARY).toBe('UPDATE_QUESTION_DICTIONARY');
});
