export const FETCH_QUESTIONS_BEGIN = 'FETCH_QUESTIONS_BEGIN';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_FAILURE = 'FETCH_QUESTIONS_FAILURE';
export const UPDATE_VOTE_IN_QUESTION_DICTIONARY =
  'UPDATE_VOTE_IN_QUESTION_DICTIONARY';
export const UPDATE_QUESTION_DICTIONARY = 'UPDATE_QUESTION_DICTIONARY';
