export const REGISTER_VOTE = 'REGISTER_VOTE';

export const POST_VOTE_BEGIN = 'POST_VOTE_BEGIN';
export const POST_VOTE_SUCCESS = 'POST_VOTE_SUCCESS';
export const POST_VOTE_FAILURE = 'POST_VOTE_FAILURE';
